apiVersion: batch/v1
kind: Job
metadata:
  generateName: work-queue-
spec:
  template:
    spec:
      containers:
      - name: work
        image: busybox
        command: ["sleep",  "300"]
        resources:
          requests:
            memory: 2Gi
            cpu: 2
      restartPolicy: Never
  parallelism: 50
  completions: 150
